export const TOKENS = {
  'color-primary': 'var(--color-primary)',
  'color-secondary': 'var(--color-secondary)',
  'color-background': 'var(--color-background)',
  'color-surface': 'var(--color-surface)',
  'color-neutral-1': 'var(--color-neutral-1)',
  'color-neutral-2': 'var(--color-neutral-2)',
  'color-neutral-3': 'var(--color-neutral-3)',
  'color-neutral-4': 'var(--color-neutral-4)',
  'color-neutral-5': 'var(--color-neutral-5)',
  'color-neutral-6': 'var(--color-neutral-6)',
  'color-neutral-7': 'var(--color-neutral-7)',
  'color-neutral-8': 'var(--color-neutral-8)',
  'color-success': 'var(--color-success)',
  'color-warning': 'var(--color-warning)',
  'color-danger': 'var(--color-danger)',
  'text-primary': 'var(--text-primary)',
  'text-secondary': 'var(--text-secondary)',
  'text-on-primary': 'var(--text-on-primary)',
  'fs-sm': 'var(--fs-sm)',
  'fs-base': 'var(--fs-base)',
  'fs-lg': 'var(--fs-lg)',
  'fs-xl': 'var(--fs-xl)',
  'fs-2xl': 'var(--fs-2xl)',
  'fs-3xl': 'var(--fs-3xl)',
  'sp-1': 'var(--sp-1)',
  'sp-2': 'var(--sp-2)',
  'sp-3': 'var(--sp-3)',
  'sp-4': 'var(--sp-4)',
  'sp-5': 'var(--sp-5)',
  'sp-6': 'var(--sp-6)',
  'sp-7': 'var(--sp-7)',
  'sp-8': 'var(--sp-8)',
  'br-sm': 'var(--br-sm)',
  'br-lg': 'var(--br-lg)',
} as const;

export type TokenName = keyof typeof TOKENS;
